spring:
  profiles:
#  TODO 默认使用 usage_message profile 用于提示在未指定 profile 时提示使用方法
#    active: usage_message  # 默认值
#    active: hello-world, sender, receiver  # hello-world 同时启动 send，receiver
#    active: work-queues, sender, receiver
#    active: pub-sub, sender, receiver
#    active: routing, sender, receiver
#    active: topics, sender, receiver
#    active: rpc, server, client
    active: confirm, sender
  rabbitmq:
#  TODO
    host: zh-home.tk


logging:
  level:
    org: error

tutorial:
  client:
    duration: 10000